### ISSUE TITLE
Error with `torusUtils.retrieveShares(...)`

### ISSUE THREAD

**Issue by johnny-woodtke** [torusresearch/torus.js#77]
Hello, I'm having issues when attempting to create a Solana wallet and return its private key using the method `torusUtils.retrieveShares(...)` as follows:

![Screen Shot 2022-08-11 at 4 37 48 PM](https://user-images.githubusercontent.com/90534770/184237891-347698e8-834a-4809-bc80-bd328114222c.png)

A basic description of our non-Torus-provided arguments are as follows:
`verifier`: A Torus-provided API key of sorts.
`verifierId`: A unique, encoded UUID associated with a user.
`jwt`: A signed JWT payload (signed with the `RS256` algorithm using the method `jsonwebtoken.sign(...)`), which has the following attributes, `sub` (which is the `verifierId`), `iat`, `iss`, and `aud`) that expires after 1 minute.

It's fairly unexpected because I've been successfully creating Torus wallets with this approach for months now, and it's all the sudden failing with the following error message on the first attempt: 

`Error occurred while verifying paramsunable to verify jwt token, [failed to verify jws signature: failed to verify message: crypto/rsa: verification error]`

Then, when I retry with the same arguments I get the following error:

`Duplicate token found`

I believe the `verifier` and `verifierId` arguments are correct because the method call, `fetchNodeDetails.getNodeDetails(...)`, works successfully. So, my instincts tell me that my `jwt` argument is incorrect/no longer compatible with the `torusUtils.retrieveShares(...)` method call.

Any advice would be greatly appreciated! Please let me know if I can provide any additional information about my situation.

**Comment by himanshuchawla009** [comment]
I discussed this issue with one of your colleague (Nicholas) and after debugging we realized that jwt token was sent as null. This issue should be fixed once you will send a valid jwt token. Feel free to reopen it if that doesn't help.

**Comment by johnny-woodtke** [comment]
Hey, we have verified that our JWT token is no longer null. This is the new error message we're receiving:

`share request could not retrieve keyIndexes: could not retrieveVerifierToKeyIndex error: retrieveVerifierToKeyIndex keyIndexes do not exist for verifier, and verifierID`

Is it possible that our private key has expired?

**Comment by chaitanyapotti** [comment]
This means.. KeyAssign is not done.
please call `getPublicAddress` first before calling `retrieveShares` for any given user.

**Comment by johnny-woodtke** [comment]
That worked! Wallet creation is back online on our end. Thanks for all the help @himanshuchawla009 @chaitanyapotti

**Comment by Lauman** [comment]
Hello everyone!
I'm having problems with the same method.
When I send the information to my backend it shows the following error:

`Error occurred while verifying paramsencoding/hex: invalid byte: U+0079 'y'.`

If I try again I get:

`Duplicate token found`

This is my code:

```
import FetchNodeDetails from "@toruslabs/fetch-node-details";
import TorusUtils from "@toruslabs/torus.js";

const postObtainPk = async (
  verifier: string,
  verifierId: string,
  idToken: string
) => {
  const fetchNodeDetails = new FetchNodeDetails();
  const torus = new TorusUtils({ network: "testnet" });
  const { torusNodeEndpoints, torusNodePub, torusIndexes } =
    await fetchNodeDetails.getNodeDetails({ verifier, verifierId });

  const publicAddress = await torus.getPublicAddress(
    torusNodeEndpoints,
    torusNodePub,
    { verifier, verifierId }
  );

  const keyData = await torus.retrieveShares(
    torusNodeEndpoints,
    torusIndexes,
    verifier,
    { verifier_id: verifierId },
    idToken
  );

  return { publicAddress, keyData };
};
```

Something that seemed strange to me is that when loading it shows this message: 

`secp256k1 unavailable, reverting to browser version`

Any help is welcome! Please let me know if I can provide any additional information.
